---
- hosts: all
  roles:
    - devetek.alertmanager
  vars:
    alertmanager_version: latest

    alertmanager_slack_api_url: "http://example.com"

    alertmanager_receivers:
      # - name: slack
      #   slack_configs:
      #     - send_resolved: true
      #       channel: '#alerts'

      - name: email
        email_configs:
          - to: 'alerts@example.com'
            from: 'alertmanager@example.com'
            smarthost: 'smtp.example.com:587'
            auth_username: 'alertmanager@example.com'
            auth_password: 'changeme'
            send_resolved: true

    alertmanager_route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: email
      # routes:
      #   - match:
      #       severity: critical
      #     receiver: slack
