---
required_packages:
  - python3
  - python3-pip
  - gcc
  - python3-dev
  - libffi-dev
  - libssl-dev
  - make
  - google-cloud-sdk

pip_packages:
  - google-auth
  - google-auth-oauthlib
  - google-auth-httplib2
  - google-api-python-client
  - google-cloud-storage
